version: "3.8"
services:
  backend:
    build: 
      context: .
      dockerfile: ./apps/backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./apps/backend:/app/apps/backend
      - ./packages:/app/packages
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  frontend:
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./apps/frontend:/app/apps/frontend
      - ./packages:/app/packages
    environment:
      - VITE_WS_URL=ws://127.0.0.1:8080
    command: npm run dev -- --host
